module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  commerce: 0
  commerce_cart: 0
  commerce_number_pattern: 0
  commerce_order: 0
  commerce_price: 0
  commerce_product: 0
  commerce_store: 0
  config: 0
  config_filter: 0
  config_split: 0
  config_translation: 0
  contextual: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  environment_indicator: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  gin_toolbar: 0
  image: 0
  inline_entity_form: 0
  inline_form_errors: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  profile: 0
  rdf: 0
  responsive_image: 0
  smtp: 0
  stage_file_proxy: 0
  state_machine: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  content_translation: 10
  views: 10
  bloom: 1000
theme:
  claro: 0
  gin: 0
profile: bloom
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: es
